### ISSUE TITLE
[Feature Request] Alarm

### ISSUE THREAD

**Issue by Pantyhose-X** [willbsp/habits#28] opened 2023-09-04 07:58 UTC
Reminder: Please use Alarm.
### Remind me with Alarm
When I'm doing other things like eating, bathing, spending time with the kids, I think it's a social app reminder. Missed time !
When I browse social application information, I will think it is a social application information reminder. I will miss the time !

**Comment by willbsp** [comment] 2023-09-09 09:14
Closing this issue, duplicate of #17.

**Closed by willbsp** 2023-09-09 09:14 UTC
